spring:
  application:
    name: portholemap-api
  mvc:
    servlet:
      path: /api

management:
  server:
    port: 8081

springdoc:
  api-docs:
    path: /api-docs
    version: OPENAPI_3_0
  swagger-ui:
    path: /swagger-ui.html
