apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 837126493345.dkr.ecr.ap-northeast-2.amazonaws.com/goormthon-1/backend:build-30
        ports:
        - containerPort: 8080
        env:
          - name: NAVER_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: NAVER_CLIENT_ID
          - name: NAVER_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: NAVER_CLIENT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 8080
